// actions/types.js
export const GET_ALL_SIGNUP_REQUEST = 'GET_ALL__SIGNUP_REQUEST';
export const GET_ALL_SIGNUP_SUCCESS = 'GET_ALL_SIGNUP_SUCCESS';
export const GET_ALL_SIGNUP_FAILURE = 'GET_ALL_SIGNUP_FAILURE';

export const GET_ALL_DISEASE_REQUEST='GET_ALL_DISEASE_REQUEST';
export const GET_ALL_DISEASE_SUCCESS='GET_ALL_DISEASE_SUCCESS';
export const GET_ALL_DISEASE_FAILURE='GET_ALL_DISEASE_FAILURE';
